---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-apps
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./manifest/flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-apps-git
  targetNamespace: flux-system

